### ISSUE TITLE
іменування стилів

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/REACT-APP#1]
https://github.com/VasylUlianovskyi/REACT-APP/blob/32e14203b43e9ad24cb7d5362763a42da80f92da/src/pages/UsersPage/UsersPages.module.sass#L36
- іменувати стилі краще в `camelCase`, так не доведеться використовувати незручні конструкції типу `styles['user-card']`, а просто `styles.userCard`.

**Comment by VasylUlianovskyi** [comment]
++
