### ISSUE TITLE
вкладеність

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/REACT-APP#2]
https://github.com/VasylUlianovskyi/REACT-APP/blob/32e14203b43e9ad24cb7d5362763a42da80f92da/src/pages/UsersPage/UsersPages.module.sass#L21-L25
- не варто зловживати вкладеністю стилів, це впливає на підтримку негативно: збільшує специфічність селектора, підвищує залежність модулів (зміна структури розмітки вимушено призведе до зміни стилів). Достатньо так:
```sass
.listContainer
  flex: 1 1 400px

.controls
  display: flex
  align-items: center
  gap: 10px
  margin-bottom: 20px
```

**Comment by VasylUlianovskyi** [comment]
++
